apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dogebot-secret-store
  namespace: dogebot
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ../secrets.json
    - name: nestedSeparator
      value: ":"
    - name: multiValued
      value: "false"
