apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dogebot-state-store
  namespace: dogebot
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        key: redisHost
        name: redisHost
    - name: redisPassword
      secretKeyRef:
        key: redisPassword
        name: redisPassword
    - name: enableTLS
      value: false
    - name: maxRetries
      value: 3
    - name: maxRetryBackoff
      value: 10
auth:
  secretStore: dogebot-secret-store